export type ParticipleKind =
  | 'kofschip-t'
  | 'kofschip-d'
  | 'stam-op-t'
  | 'geen-ge'
  | 'onregelmatig'
  | 'scheidbaar'
export type AuxKind = 'hebben' | 'zijn'

export interface PerfectItem {
  id: string
  /** Sentence split around the two gaps: before [hulpwerkwoord] middle [deelwoord] after. */
  before: string
  middle: string
  after: string
  infinitive: string
  gloss: string
  /** The hebben-form and the zijn-form for this subject, in that order. */
  auxOptions: [string, string]
  aux: string
  auxKind: AuxKind
  participle: string
  kind: ParticipleKind
}

export const KIND_LABELS: Record<ParticipleKind, string> = {
  'kofschip-t': "'t kofschip: -t",
  'kofschip-d': "'t kofschip: -d",
  'stam-op-t': 'Stem ends in -t',
  'geen-ge': 'No ge- prefix',
  onregelmatig: 'Irregular',
  scheidbaar: 'Separable verb',
}

export const KIND_EXPLANATIONS: Record<ParticipleKind, string> = {
  'kofschip-t':
    "The stem ends in a letter from 't kofschip (t, k, f, s, ch, p), so the participle is ge- + stem + -t.",
  'kofschip-d':
    "The stem does not end in a letter from 't kofschip, so the participle is ge- + stem + -d.",
  'stam-op-t': 'The stem already ends in -t, so no second -t is added.',
  'geen-ge':
    'Verbs starting with be-, ge-, ver-, ont- or her- take no ge- in the past participle.',
  onregelmatig: 'This participle is irregular, so the form has to be memorised.',
  scheidbaar:
    'With a separable verb the ge- does not go at the front but in the middle: op + ge + beld = opgebeld. The participle is still written as one word.',
}

export const AUX_EXPLANATIONS: Record<AuxKind, string> = {
  hebben: 'Most verbs take hebben.',
  zijn: 'Verbs of change, or of movement to a place, take zijn: gaan, komen, blijven, worden, zijn, beginnen, verhuizen, vertrekken, gebeuren.',
}

/** Shown in the game as a reminder panel. */
export const KOFSCHIP_LETTERS = ['t', 'k', 'f', 's', 'ch', 'p']

export const items: PerfectItem[] = [
  {
    id: 'p1',
    before: 'Gisteren',
    middle: 'ik de hele dag',
    after: '.',
    infinitive: 'werken',
    gloss: 'to work',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'gewerkt',
    kind: 'kofschip-t',
  },
  {
    id: 'p2',
    before: 'Mijn man',
    middle: 'gisteravond',
    after: '.',
    infinitive: 'koken',
    gloss: 'to cook',
    auxOptions: ['heeft', 'is'],
    aux: 'heeft',
    auxKind: 'hebben',
    participle: 'gekookt',
    kind: 'kofschip-t',
  },
  {
    id: 'p3',
    before: 'Ik',
    middle: 'de bus',
    after: '.',
    infinitive: 'missen',
    gloss: 'to miss',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'gemist',
    kind: 'kofschip-t',
  },
  {
    id: 'p4',
    before: 'Wij',
    middle: 'vijf jaar in Delft',
    after: '.',
    infinitive: 'wonen',
    gloss: 'to live',
    auxOptions: ['hebben', 'zijn'],
    aux: 'hebben',
    auxKind: 'hebben',
    participle: 'gewoond',
    kind: 'kofschip-d',
  },
  {
    id: 'p5',
    before: 'Ik',
    middle: 'veel nieuwe woorden',
    after: '.',
    infinitive: 'leren',
    gloss: 'to learn',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'geleerd',
    kind: 'kofschip-d',
  },
  {
    id: 'p6',
    before: 'Ik',
    middle: 'de huisarts',
    after: '.',
    infinitive: 'bellen',
    gloss: 'to call, to phone',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'gebeld',
    kind: 'kofschip-d',
  },
  {
    id: 'p7',
    before: 'Mijn dochter',
    middle: 'de hele middag buiten',
    after: '.',
    infinitive: 'spelen',
    gloss: 'to play',
    auxOptions: ['heeft', 'is'],
    aux: 'heeft',
    auxKind: 'hebben',
    participle: 'gespeeld',
    kind: 'kofschip-d',
  },
  {
    id: 'p8',
    before: 'Wij',
    middle: 'gisteren lang met de buren',
    after: '.',
    infinitive: 'praten',
    gloss: 'to talk',
    auxOptions: ['hebben', 'zijn'],
    aux: 'hebben',
    auxKind: 'hebben',
    participle: 'gepraat',
    kind: 'stam-op-t',
  },
  {
    id: 'p9',
    before: 'Ik',
    middle: 'de rekening al',
    after: '.',
    infinitive: 'betalen',
    gloss: 'to pay',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'betaald',
    kind: 'geen-ge',
  },
  {
    id: 'p10',
    before: 'Hij',
    middle: 'mij niets over de afspraak',
    after: '.',
    infinitive: 'vertellen',
    gloss: 'to tell',
    auxOptions: ['heeft', 'is'],
    aux: 'heeft',
    auxKind: 'hebben',
    participle: 'verteld',
    kind: 'geen-ge',
  },
  {
    id: 'p11',
    before: 'Ik',
    middle: 'mijn buurvrouw vorige week',
    after: '.',
    infinitive: 'ontmoeten',
    gloss: 'to meet',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'ontmoet',
    kind: 'geen-ge',
  },
  {
    id: 'p12',
    before: 'Wij',
    middle: 'vorige maand',
    after: '.',
    infinitive: 'verhuizen',
    gloss: 'to move house',
    auxOptions: ['hebben', 'zijn'],
    aux: 'zijn',
    auxKind: 'zijn',
    participle: 'verhuisd',
    kind: 'geen-ge',
  },
  {
    id: 'p13',
    before: 'De les',
    middle: 'om negen uur',
    after: '.',
    infinitive: 'beginnen',
    gloss: 'to begin',
    auxOptions: ['heeft', 'is'],
    aux: 'is',
    auxKind: 'zijn',
    participle: 'begonnen',
    kind: 'geen-ge',
  },
  {
    id: 'p14',
    before: 'Wat',
    middle: 'er precies',
    after: '?',
    infinitive: 'gebeuren',
    gloss: 'to happen',
    auxOptions: ['heeft', 'is'],
    aux: 'is',
    auxKind: 'zijn',
    participle: 'gebeurd',
    kind: 'geen-ge',
  },
  {
    id: 'p15',
    before: 'Ik',
    middle: 'vanmiddag al',
    after: '.',
    infinitive: 'eten',
    gloss: 'to eat',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'gegeten',
    kind: 'onregelmatig',
  },
  {
    id: 'p16',
    before: 'Wij',
    middle: 'op het feest veel koffie',
    after: '.',
    infinitive: 'drinken',
    gloss: 'to drink',
    auxOptions: ['hebben', 'zijn'],
    aux: 'hebben',
    auxKind: 'hebben',
    participle: 'gedronken',
    kind: 'onregelmatig',
  },
  {
    id: 'p17',
    before: 'Ik',
    middle: 'uw brief',
    after: '.',
    infinitive: 'lezen',
    gloss: 'to read',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'gelezen',
    kind: 'onregelmatig',
  },
  {
    id: 'p18',
    before: 'Ik',
    middle: 'u vorige week een e-mail',
    after: '.',
    infinitive: 'schrijven',
    gloss: 'to write',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'geschreven',
    kind: 'onregelmatig',
  },
  {
    id: 'p19',
    before: 'Ik',
    middle: 'de dokter nog niet',
    after: '.',
    infinitive: 'zien',
    gloss: 'to see',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'gezien',
    kind: 'onregelmatig',
  },
  {
    id: 'p20',
    before: 'Gisteren',
    middle: 'ik de boodschappen',
    after: '.',
    infinitive: 'doen',
    gloss: 'to do',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'gedaan',
    kind: 'onregelmatig',
  },
  {
    id: 'p21',
    before: 'Ik',
    middle: 'gisteren geen tijd',
    after: '.',
    infinitive: 'hebben',
    gloss: 'to have',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'gehad',
    kind: 'onregelmatig',
  },
  {
    id: 'p22',
    before: 'Ik',
    middle: 'een brief van de gemeente',
    after: '.',
    infinitive: 'krijgen',
    gloss: 'to receive',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'gekregen',
    kind: 'onregelmatig',
  },
  {
    id: 'p23',
    before: 'Ik',
    middle: 'gisteren naar de tandarts',
    after: '.',
    infinitive: 'gaan',
    gloss: 'to go',
    auxOptions: ['heb', 'ben'],
    aux: 'ben',
    auxKind: 'zijn',
    participle: 'gegaan',
    kind: 'onregelmatig',
  },
  {
    id: 'p24',
    before: 'Hij',
    middle: 'vanmorgen te laat',
    after: '.',
    infinitive: 'komen',
    gloss: 'to come',
    auxOptions: ['heeft', 'is'],
    aux: 'is',
    auxKind: 'zijn',
    participle: 'gekomen',
    kind: 'onregelmatig',
  },
  {
    id: 'p25',
    before: 'Ik',
    middle: 'vorige week bij de dokter',
    after: '.',
    infinitive: 'zijn',
    gloss: 'to be',
    auxOptions: ['heb', 'ben'],
    aux: 'ben',
    auxKind: 'zijn',
    participle: 'geweest',
    kind: 'onregelmatig',
  },
  {
    id: 'p26',
    before: 'Ik',
    middle: 'met griep thuis',
    after: '.',
    infinitive: 'blijven',
    gloss: 'to stay',
    auxOptions: ['heb', 'ben'],
    aux: 'ben',
    auxKind: 'zijn',
    participle: 'gebleven',
    kind: 'onregelmatig',
  },
  {
    id: 'p27',
    before: 'De trein',
    middle: 'al',
    after: '.',
    infinitive: 'vertrekken',
    gloss: 'to depart',
    auxOptions: ['heeft', 'is'],
    aux: 'is',
    auxKind: 'zijn',
    participle: 'vertrokken',
    kind: 'geen-ge',
  },
  {
    id: 'p28',
    before: 'Ik',
    middle: 'mijn baas gisteren',
    after: '.',
    infinitive: 'opbellen',
    gloss: 'to call up',
    auxOptions: ['heb', 'ben'],
    aux: 'heb',
    auxKind: 'hebben',
    participle: 'opgebeld',
    kind: 'scheidbaar',
  },
  {
    id: 'p29',
    before: 'Zij',
    middle: 'haar zoon',
    after: '.',
    infinitive: 'meenemen',
    gloss: 'to bring along',
    auxOptions: ['heeft', 'is'],
    aux: 'heeft',
    auxKind: 'hebben',
    participle: 'meegenomen',
    kind: 'scheidbaar',
  },
  {
    id: 'p30',
    before: 'Wij',
    middle: 'de afspraak',
    after: '.',
    infinitive: 'afzeggen',
    gloss: 'to cancel',
    auxOptions: ['hebben', 'zijn'],
    aux: 'hebben',
    auxKind: 'hebben',
    participle: 'afgezegd',
    kind: 'scheidbaar',
  },
  {
    id: 'p31',
    before: 'Hij',
    middle: 'het formulier',
    after: '.',
    infinitive: 'invullen',
    gloss: 'to fill in',
    auxOptions: ['heeft', 'is'],
    aux: 'heeft',
    auxKind: 'hebben',
    participle: 'ingevuld',
    kind: 'scheidbaar',
  },
  {
    id: 'p32',
    before: 'De trein',
    middle: 'om acht uur',
    after: '.',
    infinitive: 'aankomen',
    gloss: 'to arrive',
    auxOptions: ['heeft', 'is'],
    aux: 'is',
    auxKind: 'zijn',
    participle: 'aangekomen',
    kind: 'scheidbaar',
  },
  {
    id: 'p33',
    before: 'Ik',
    middle: 'vanmorgen vroeg',
    after: '.',
    infinitive: 'opstaan',
    gloss: 'to get up',
    auxOptions: ['heb', 'ben'],
    aux: 'ben',
    auxKind: 'zijn',
    participle: 'opgestaan',
    kind: 'scheidbaar',
  },
]
