/**
 * Dutch → English glosses for the words that appear in game texts, so any Dutch
 * sentence can be rendered with per-word tooltips (AGENTS.md section 7) without
 * hand-writing a gloss next to every sentence.
 *
 * `verb: true` gets the amber verb marker. Words that are a noun in one reading
 * and a verb form in another (werk, vraag, antwoord, fiets, post, bericht) are
 * deliberately NOT marked as verbs: colouring them amber would be wrong as
 * often as it is right. Their gloss names both senses instead.
 */
export interface GlossEntry {
  gloss: string
  verb?: boolean
}

export const glossary: Record<string, GlossEntry> = {
  // Pronouns and determiners
  ik: { gloss: 'I' },
  jij: { gloss: 'you (informal)' },
  je: { gloss: 'you; your' },
  u: { gloss: 'you (formal)' },
  uw: { gloss: 'your (formal)' },
  jou: { gloss: 'you …' },
  jouw: { gloss: 'your (informal)' },
  hij: { gloss: 'he' },
  zij: { gloss: 'she; they' },
  ze: { gloss: 'she; they' },
  het: { gloss: 'the; it' },
  we: { gloss: 'we' },
  wij: { gloss: 'we' },
  jullie: { gloss: 'you (plural)' },
  mij: { gloss: 'me' },
  me: { gloss: 'me' },
  mijn: { gloss: 'my' },
  haar: { gloss: 'her' },
  ons: { gloss: 'us; our' },
  onze: { gloss: 'our' },
  hun: { gloss: 'their' },
  deze: { gloss: 'this; these' },
  dit: { gloss: 'this' },
  die: { gloss: 'that …' },
  dat: { gloss: 'that' },
  er: { gloss: 'there' },
  elkaar: { gloss: 'each other' },
  zelf: { gloss: 'self' },
  de: { gloss: 'the' },
  een: { gloss: 'a; one' },
  geen: { gloss: 'no …' },
  iets: { gloss: 'something' },
  niets: { gloss: 'nothing' },
  iemand: { gloss: 'someone' },
  niemand: { gloss: 'nobody' },
  alles: { gloss: 'everything' },
  allemaal: { gloss: 'all' },
  alle: { gloss: 'all' },
  ander: { gloss: 'other' },
  andere: { gloss: 'other' },

  // Question words
  wie: { gloss: 'who' },
  wat: { gloss: 'what' },
  waar: { gloss: 'where' },
  wanneer: { gloss: 'when' },
  waarom: { gloss: 'why' },
  hoe: { gloss: 'how' },
  hoeveel: { gloss: 'how many …' },
  hoelang: { gloss: 'how long' },
  welke: { gloss: 'which' },
  welk: { gloss: 'which' },
  vandaan: { gloss: 'from …' },

  // Connectors and common adverbs
  en: { gloss: 'and' },
  maar: { gloss: 'but' },
  want: { gloss: 'because (verb 2nd)' },
  dus: { gloss: 'so, therefore' },
  omdat: { gloss: 'because (verb last)' },
  als: { gloss: 'if, when' },
  of: { gloss: 'or; whether' },
  niet: { gloss: 'not' },
  wel: { gloss: 'indeed …' },
  ook: { gloss: 'also, too' },
  al: { gloss: 'already' },
  nog: { gloss: 'still, yet' },
  altijd: { gloss: 'always' },
  nooit: { gloss: 'never' },
  soms: { gloss: 'sometimes' },
  vaak: { gloss: 'often' },
  meestal: { gloss: 'usually' },
  daarom: { gloss: 'therefore' },
  daarna: { gloss: 'after that' },
  dan: { gloss: 'then' },
  toch: { gloss: 'still …' },
  even: { gloss: 'briefly, just' },
  graag: { gloss: 'gladly, please' },
  alvast: { gloss: 'in advance' },
  helaas: { gloss: 'unfortunately' },
  precies: { gloss: 'exactly' },
  samen: { gloss: 'together' },
  terug: { gloss: 'back' },
  weer: { gloss: 'again' },
  snel: { gloss: 'quick, fast' },
  zo: { gloss: 'so …' },
  heel: { gloss: 'very; whole' },
  erg: { gloss: 'very; bad' },
  veel: { gloss: 'much, many' },
  weinig: { gloss: 'little, few' },
  misschien: { gloss: 'maybe' },
  straks: { gloss: 'later today' },
  nu: { gloss: 'now' },
  hierbij: { gloss: 'herewith' },
  ja: { gloss: 'yes' },
  nee: { gloss: 'no' },
  sorry: { gloss: 'sorry' },
  bedankt: { gloss: 'thank you' },
  dank: { gloss: 'thanks' },
  spijt: { gloss: 'regret …' },
  alstublieft: { gloss: 'please (formal)' },
  alsjeblieft: { gloss: 'please (informal)' },

  // Time words
  vandaag: { gloss: 'today' },
  morgen: { gloss: 'tomorrow; morning' },
  gisteren: { gloss: 'yesterday' },
  overmorgen: { gloss: 'the day after tomorrow' },
  gisteravond: { gloss: 'last night' },
  vanavond: { gloss: 'this evening' },
  vanmiddag: { gloss: 'this afternoon' },
  vanmorgen: { gloss: 'this morning' },
  vanochtend: { gloss: 'this morning' },
  volgende: { gloss: 'next' },
  vorige: { gloss: 'last, previous' },
  ochtend: { gloss: 'morning' },
  morgenochtend: { gloss: 'tomorrow morning' },
  middag: { gloss: 'afternoon' },
  avond: { gloss: 'evening' },
  nacht: { gloss: 'night' },
  weekend: { gloss: 'weekend' },
  werkdagen: { gloss: 'working days' },
  maandag: { gloss: 'Monday' },
  dinsdag: { gloss: 'Tuesday' },
  woensdag: { gloss: 'Wednesday' },
  donderdag: { gloss: 'Thursday' },
  vrijdag: { gloss: 'Friday' },
  zaterdag: { gloss: 'Saturday' },
  zondag: { gloss: 'Sunday' },
  januari: { gloss: 'January' },
  februari: { gloss: 'February' },
  maart: { gloss: 'March' },
  april: { gloss: 'April' },
  mei: { gloss: 'May' },
  juni: { gloss: 'June' },
  juli: { gloss: 'July' },
  augustus: { gloss: 'August' },
  september: { gloss: 'September' },
  oktober: { gloss: 'October' },
  november: { gloss: 'November' },
  december: { gloss: 'December' },

  // Prepositions
  in: { gloss: 'in' },
  op: { gloss: 'on …' },
  aan: { gloss: 'to, on' },
  bij: { gloss: 'at …' },
  van: { gloss: 'of, from' },
  voor: { gloss: 'for, before' },
  naar: { gloss: 'to, towards' },
  met: { gloss: 'with' },
  over: { gloss: 'about …' },
  om: { gloss: 'at; to …' },
  uit: { gloss: 'out …' },
  tot: { gloss: 'until' },
  tussen: { gloss: 'between' },
  na: { gloss: 'after' },
  door: { gloss: 'through, by' },
  zonder: { gloss: 'without' },
  onder: { gloss: 'under' },
  achter: { gloss: 'behind' },
  naast: { gloss: 'next to' },
  tegen: { gloss: 'against; to' },
  sinds: { gloss: 'since' },
  langs: { gloss: 'by, past' },
  binnen: { gloss: 'within, inside' },

  // zijn
  zijn: { gloss: 'to be; his', verb: true },
  ben: { gloss: 'am', verb: true },
  bent: { gloss: 'are', verb: true },
  is: { gloss: 'is', verb: true },
  was: { gloss: 'was', verb: true },
  waren: { gloss: 'were', verb: true },
  geweest: { gloss: 'been', verb: true },

  // hebben
  hebben: { gloss: 'to have', verb: true },
  heb: { gloss: 'have', verb: true },
  hebt: { gloss: 'have', verb: true },
  heeft: { gloss: 'has', verb: true },
  had: { gloss: 'had', verb: true },
  hadden: { gloss: 'had (plural)', verb: true },
  gehad: { gloss: 'had (participle)', verb: true },

  // Modals
  kunnen: { gloss: 'can …', verb: true },
  kan: { gloss: 'can', verb: true },
  kun: { gloss: 'can (you)', verb: true },
  kunt: { gloss: 'can', verb: true },
  moeten: { gloss: 'must …', verb: true },
  moet: { gloss: 'must', verb: true },
  willen: { gloss: 'to want', verb: true },
  wil: { gloss: 'want', verb: true },
  wilt: { gloss: 'want (you)', verb: true },
  mogen: { gloss: 'may …', verb: true },
  mag: { gloss: 'may', verb: true },
  zal: { gloss: 'will', verb: true },
  zullen: { gloss: 'will, shall', verb: true },

  // Other verbs
  gaan: { gloss: 'to go', verb: true },
  ga: { gloss: 'go', verb: true },
  gaat: { gloss: 'goes', verb: true },
  gegaan: { gloss: 'gone', verb: true },
  komen: { gloss: 'to come', verb: true },
  kom: { gloss: 'come', verb: true },
  komt: { gloss: 'comes', verb: true },
  gekomen: { gloss: 'come (participle)', verb: true },
  doen: { gloss: 'to do', verb: true },
  doe: { gloss: 'do', verb: true },
  doet: { gloss: 'does', verb: true },
  gedaan: { gloss: 'done', verb: true },
  werken: { gloss: 'to work', verb: true },
  werkt: { gloss: 'works', verb: true },
  gewerkt: { gloss: 'worked', verb: true },
  wonen: { gloss: 'to live', verb: true },
  woon: { gloss: 'live', verb: true },
  woont: { gloss: 'lives', verb: true },
  gewoond: { gloss: 'lived', verb: true },
  leren: { gloss: 'to learn', verb: true },
  leer: { gloss: 'learn', verb: true },
  leert: { gloss: 'learns', verb: true },
  geleerd: { gloss: 'learned', verb: true },
  maken: { gloss: 'to make', verb: true },
  maak: { gloss: 'make', verb: true },
  maakt: { gloss: 'makes', verb: true },
  gemaakt: { gloss: 'made', verb: true },
  lopen: { gloss: 'to walk', verb: true },
  loop: { gloss: 'walk', verb: true },
  loopt: { gloss: 'walks', verb: true },
  eten: { gloss: 'to eat', verb: true },
  eet: { gloss: 'eat, eats', verb: true },
  gegeten: { gloss: 'eaten', verb: true },
  drinken: { gloss: 'to drink', verb: true },
  drink: { gloss: 'drink', verb: true },
  drinkt: { gloss: 'drinks', verb: true },
  gedronken: { gloss: 'drunk (participle)', verb: true },
  lezen: { gloss: 'to read', verb: true },
  lees: { gloss: 'read', verb: true },
  leest: { gloss: 'reads', verb: true },
  gelezen: { gloss: 'read (participle)', verb: true },
  schrijven: { gloss: 'to write', verb: true },
  schrijf: { gloss: 'write', verb: true },
  schrijft: { gloss: 'writes', verb: true },
  geschreven: { gloss: 'written', verb: true },
  spreken: { gloss: 'to speak', verb: true },
  spreek: { gloss: 'speak', verb: true },
  spreekt: { gloss: 'speaks', verb: true },
  zien: { gloss: 'to see', verb: true },
  zie: { gloss: 'see', verb: true },
  ziet: { gloss: 'sees', verb: true },
  gezien: { gloss: 'seen', verb: true },
  weten: { gloss: 'to know (a fact)', verb: true },
  weet: { gloss: 'know, knows', verb: true },
  denken: { gloss: 'to think', verb: true },
  denk: { gloss: 'think', verb: true },
  denkt: { gloss: 'thinks', verb: true },
  gedacht: { gloss: 'thought', verb: true },
  vinden: { gloss: 'to find …', verb: true },
  vindt: { gloss: 'finds; thinks', verb: true },
  geven: { gloss: 'to give', verb: true },
  geef: { gloss: 'give', verb: true },
  geeft: { gloss: 'gives', verb: true },
  gegeven: { gloss: 'given', verb: true },
  krijgen: { gloss: 'to get', verb: true },
  krijg: { gloss: 'get', verb: true },
  krijgt: { gloss: 'gets', verb: true },
  gekregen: { gloss: 'received', verb: true },
  nemen: { gloss: 'to take', verb: true },
  neem: { gloss: 'take', verb: true },
  neemt: { gloss: 'takes', verb: true },
  genomen: { gloss: 'taken', verb: true },
  brengen: { gloss: 'to bring', verb: true },
  breng: { gloss: 'bring', verb: true },
  brengt: { gloss: 'brings', verb: true },
  gebracht: { gloss: 'brought', verb: true },
  kopen: { gloss: 'to buy', verb: true },
  koopt: { gloss: 'buys', verb: true },
  gekocht: { gloss: 'bought', verb: true },
  zoeken: { gloss: 'to search', verb: true },
  zoekt: { gloss: 'looks for', verb: true },
  gezocht: { gloss: 'looked for', verb: true },
  bellen: { gloss: 'to call', verb: true },
  bel: { gloss: 'call', verb: true },
  belt: { gloss: 'calls', verb: true },
  gebeld: { gloss: 'called', verb: true },
  betalen: { gloss: 'to pay', verb: true },
  betaal: { gloss: 'pay', verb: true },
  betaalt: { gloss: 'pays', verb: true },
  betaald: { gloss: 'paid', verb: true },
  blijven: { gloss: 'to stay', verb: true },
  blijf: { gloss: 'stay', verb: true },
  blijft: { gloss: 'stays', verb: true },
  gebleven: { gloss: 'stayed', verb: true },
  beginnen: { gloss: 'to begin', verb: true },
  begin: { gloss: 'begin', verb: true },
  begint: { gloss: 'begins', verb: true },
  begonnen: { gloss: 'begun', verb: true },
  heten: { gloss: 'to be called', verb: true },
  heet: { gloss: 'am/is called', verb: true },
  zitten: { gloss: 'to sit', verb: true },
  zit: { gloss: 'sit, sits', verb: true },
  gezeten: { gloss: 'sat', verb: true },
  staan: { gloss: 'to stand', verb: true },
  staat: { gloss: 'stands …', verb: true },
  gestaan: { gloss: 'stood', verb: true },
  slapen: { gloss: 'to sleep', verb: true },
  slaapt: { gloss: 'sleeps', verb: true },
  geslapen: { gloss: 'slept', verb: true },
  helpen: { gloss: 'to help', verb: true },
  helpt: { gloss: 'helps', verb: true },
  geholpen: { gloss: 'helped', verb: true },
  vragen: { gloss: 'to ask …', verb: true },
  vraagt: { gloss: 'asks', verb: true },
  gevraagd: { gloss: 'asked', verb: true },
  antwoorden: { gloss: 'to answer …', verb: true },
  antwoordt: { gloss: 'answers', verb: true },
  vertellen: { gloss: 'to tell', verb: true },
  vertel: { gloss: 'tell', verb: true },
  vertelt: { gloss: 'tells', verb: true },
  verteld: { gloss: 'told', verb: true },
  ontmoeten: { gloss: 'to meet', verb: true },
  ontmoet: { gloss: 'meets; met', verb: true },
  verhuizen: { gloss: 'to move …', verb: true },
  verhuisd: { gloss: 'moved house', verb: true },
  gebeuren: { gloss: 'to happen', verb: true },
  gebeurt: { gloss: 'happens', verb: true },
  gebeurd: { gloss: 'happened', verb: true },
  vertrekken: { gloss: 'to leave', verb: true },
  vertrokken: { gloss: 'departed', verb: true },
  missen: { gloss: 'to miss', verb: true },
  mist: { gloss: 'misses', verb: true },
  gemist: { gloss: 'missed', verb: true },
  koken: { gloss: 'to cook', verb: true },
  kookt: { gloss: 'cooks', verb: true },
  gekookt: { gloss: 'cooked', verb: true },
  fietsen: { gloss: 'to cycle …', verb: true },
  gefietst: { gloss: 'cycled', verb: true },
  spelen: { gloss: 'to play', verb: true },
  speelt: { gloss: 'plays', verb: true },
  gespeeld: { gloss: 'played', verb: true },
  praten: { gloss: 'to talk', verb: true },
  praat: { gloss: 'talk, talks', verb: true },
  gepraat: { gloss: 'talked', verb: true },
  studeren: { gloss: 'to study', verb: true },
  studeer: { gloss: 'study', verb: true },
  gestudeerd: { gloss: 'studied', verb: true },
  horen: { gloss: 'to hear', verb: true },
  hoor: { gloss: 'hear', verb: true },
  hoort: { gloss: 'hears; belongs', verb: true },
  gehoord: { gloss: 'heard', verb: true },
  worden: { gloss: 'to become', verb: true },
  wordt: { gloss: 'becomes', verb: true },
  geworden: { gloss: 'become', verb: true },
  houden: { gloss: 'to hold …', verb: true },
  houdt: { gloss: 'holds; likes', verb: true },
  rijden: { gloss: 'to drive', verb: true },
  rijdt: { gloss: 'drives', verb: true },
  gereden: { gloss: 'driven', verb: true },
  sturen: { gloss: 'to send', verb: true },
  stuur: { gloss: 'send', verb: true },
  stuurt: { gloss: 'sends', verb: true },
  gestuurd: { gloss: 'sent', verb: true },
  laten: { gloss: 'to let …', verb: true },
  laat: { gloss: 'let; late', verb: true },
  passen: { gloss: 'to fit …', verb: true },
  past: { gloss: 'fits, suits', verb: true },
  gepast: { gloss: 'fitted …', verb: true },
  duren: { gloss: 'to last', verb: true },
  duurt: { gloss: 'lasts', verb: true },
  kosten: { gloss: 'to cost …', verb: true },
  kost: { gloss: 'costs', verb: true },
  begrijpen: { gloss: 'to understand', verb: true },
  begrijp: { gloss: 'understand', verb: true },
  begrijpt: { gloss: 'understands', verb: true },
  voelen: { gloss: 'to feel', verb: true },
  voel: { gloss: 'feel', verb: true },
  voelt: { gloss: 'feels', verb: true },
  kennen: { gloss: 'to know (a person)', verb: true },
  ken: { gloss: 'know', verb: true },
  kent: { gloss: 'knows', verb: true },
  inburgeren: { gloss: 'to integrate', verb: true },
  overwerken: { gloss: 'to work overtime', verb: true },
  langskomen: { gloss: 'to drop by', verb: true },
  repareren: { gloss: 'to repair', verb: true },
  oplossen: { gloss: 'to solve', verb: true },
  uitleggen: { gloss: 'to explain', verb: true },
  uitnodigen: { gloss: 'to invite', verb: true },
  logeren: { gloss: 'to stay over', verb: true },
  verwacht: { gloss: 'expect, expects', verb: true },
  bijwerken: { gloss: 'to catch up', verb: true },
  verzetten: { gloss: 'to reschedule', verb: true },
  afzeggen: { gloss: 'to cancel', verb: true },
  opbellen: { gloss: 'to call up', verb: true },
  opgebeld: { gloss: 'called up', verb: true },
  meenemen: { gloss: 'to bring along', verb: true },
  meegenomen: { gloss: 'brought along', verb: true },
  afgezegd: { gloss: 'cancelled', verb: true },
  invullen: { gloss: 'to fill in', verb: true },
  ingevuld: { gloss: 'filled in', verb: true },
  aankomen: { gloss: 'to arrive', verb: true },
  aangekomen: { gloss: 'arrived', verb: true },
  opstaan: { gloss: 'to get up', verb: true },
  opgestaan: { gloss: 'got up', verb: true },
  ontvangen: { gloss: 'to receive …', verb: true },
  vervangen: { gloss: 'to replace', verb: true },
  aannemen: { gloss: 'to accept …', verb: true },
  opzeggen: { gloss: 'to cancel', verb: true },
  halen: { gloss: 'to fetch', verb: true },

  // People
  man: { gloss: 'man; husband' },
  vrouw: { gloss: 'woman; wife' },
  kind: { gloss: 'child' },
  kinderen: { gloss: 'children' },
  dochter: { gloss: 'daughter' },
  zoon: { gloss: 'son' },
  zus: { gloss: 'sister' },
  broer: { gloss: 'brother' },
  ouders: { gloss: 'parents' },
  oma: { gloss: 'grandma' },
  buurvrouw: { gloss: 'female neighbour' },
  buurman: { gloss: 'male neighbour' },
  buren: { gloss: 'neighbours' },
  vriend: { gloss: 'friend' },
  collega: { gloss: 'colleague' },
  baas: { gloss: 'boss' },
  leidinggevende: { gloss: 'manager' },
  dokter: { gloss: 'doctor' },
  huisarts: { gloss: 'GP …' },
  tandarts: { gloss: 'dentist' },
  monteur: { gloss: 'repair technician' },
  verhuurder: { gloss: 'landlord' },
  klant: { gloss: 'customer' },
  meisje: { gloss: 'girl' },
  heer: { gloss: 'sir, gentleman' },
  mevrouw: { gloss: 'madam, Mrs' },
  meneer: { gloss: 'sir, Mr' },
  bewoner: { gloss: 'resident' },

  // Places and things
  gemeente: { gloss: 'municipality' },
  school: { gloss: 'school' },
  les: { gloss: 'lesson' },
  cursus: { gloss: 'course' },
  huiswerk: { gloss: 'homework' },
  werk: { gloss: 'work …' },
  afspraak: { gloss: 'appointment' },
  bericht: { gloss: 'message' },
  brief: { gloss: 'letter' },
  formulier: { gloss: 'form' },
  aanhef: { gloss: 'opening, salutation' },
  afsluiting: { gloss: 'closing' },
  naam: { gloss: 'name' },
  voornaam: { gloss: 'first name' },
  achternaam: { gloss: 'surname' },
  geboortedatum: { gloss: 'birth date' },
  geboorteplaats: { gloss: 'birth place' },
  nationaliteit: { gloss: 'nationality' },
  burgerservicenummer: { gloss: 'citizen number' },
  postcode: { gloss: 'postal code' },
  woonplaats: { gloss: 'hometown' },
  adres: { gloss: 'address' },
  straat: { gloss: 'street' },
  huisnummer: { gloss: 'house number' },
  telefoonnummer: { gloss: 'phone number' },
  handtekening: { gloss: 'signature' },
  datum: { gloss: 'date' },
  tijd: { gloss: 'time' },
  uur: { gloss: 'hour, o’clock' },
  dag: { gloss: 'day' },
  dagen: { gloss: 'days' },
  week: { gloss: 'week' },
  weken: { gloss: 'weeks' },
  maand: { gloss: 'month' },
  maanden: { gloss: 'months' },
  jaar: { gloss: 'year' },
  jaren: { gloss: 'years' },
  vakantie: { gloss: 'holiday' },
  huis: { gloss: 'house' },
  huizen: { gloss: 'houses' },
  woning: { gloss: 'home, dwelling' },
  flat: { gloss: 'flat, apartment' },
  kamer: { gloss: 'room' },
  woonkamer: { gloss: 'living room' },
  raam: { gloss: 'window' },
  ramen: { gloss: 'windows' },
  deur: { gloss: 'door' },
  tafel: { gloss: 'table' },
  stoel: { gloss: 'chair' },
  stoelen: { gloss: 'chairs' },
  sleutel: { gloss: 'key' },
  sleutels: { gloss: 'keys' },
  fiets: { gloss: 'bicycle …' },
  auto: { gloss: 'car' },
  bus: { gloss: 'bus' },
  trein: { gloss: 'train' },
  station: { gloss: 'station' },
  ziekenhuis: { gloss: 'hospital' },
  winkel: { gloss: 'shop' },
  bakkerij: { gloss: 'bakery' },
  boodschappen: { gloss: 'groceries' },
  brood: { gloss: 'bread' },
  koffie: { gloss: 'coffee' },
  thee: { gloss: 'tea' },
  water: { gloss: 'water' },
  planten: { gloss: 'plants' },
  bloemen: { gloss: 'flowers' },
  geld: { gloss: 'money' },
  prijs: { gloss: 'price' },
  prijzen: { gloss: 'prices' },
  euro: { gloss: 'euro' },
  verwarming: { gloss: 'heating' },
  radiator: { gloss: 'radiator' },
  post: { gloss: 'post, mail' },
  brievenbus: { gloss: 'letterbox' },
  pakket: { gloss: 'parcel' },
  feest: { gloss: 'party' },
  feestje: { gloss: 'small party' },
  verjaardag: { gloss: 'birthday' },
  klacht: { gloss: 'complaint' },
  griep: { gloss: 'flu' },
  koorts: { gloss: 'fever' },
  hoofdpijn: { gloss: 'headache' },
  honger: { gloss: 'hunger' },
  kies: { gloss: 'molar, tooth' },
  vraag: { gloss: 'question …' },
  antwoord: { gloss: 'answer' },
  woord: { gloss: 'word' },
  woorden: { gloss: 'words' },
  zin: { gloss: 'sentence' },
  zinnen: { gloss: 'sentences' },
  boek: { gloss: 'book' },
  foto: { gloss: 'photo' },
  stad: { gloss: 'city' },
  steden: { gloss: 'cities' },
  land: { gloss: 'country' },
  nederlands: { gloss: 'Dutch' },
  gesprek: { gloss: 'conversation' },
  groep: { gloss: 'group …' },
  kat: { gloss: 'cat' },
  katten: { gloss: 'cats' },
  boom: { gloss: 'tree' },
  bomen: { gloss: 'trees' },
  ei: { gloss: 'egg' },
  eieren: { gloss: 'eggs' },
  kopje: { gloss: 'cup' },
  lessen: { gloss: 'lessons' },
  mannen: { gloss: 'men' },
  vergadering: { gloss: 'meeting' },
  gezondheid: { gloss: 'health' },
  informatie: { gloss: 'information' },
  praktijk: { gloss: 'practice (medical)' },
  papieren: { gloss: 'papers, documents' },
  rekening: { gloss: 'bill' },

  // Adjectives
  goed: { gloss: 'good, well' },
  slecht: { gloss: 'bad' },
  groot: { gloss: 'big' },
  grote: { gloss: 'big' },
  klein: { gloss: 'small' },
  kleine: { gloss: 'small' },
  nieuw: { gloss: 'new' },
  nieuwe: { gloss: 'new' },
  oud: { gloss: 'old' },
  jong: { gloss: 'young' },
  ziek: { gloss: 'ill, sick' },
  beter: { gloss: 'better' },
  moeilijk: { gloss: 'difficult' },
  moeilijke: { gloss: 'difficult' },
  makkelijk: { gloss: 'easy' },
  lang: { gloss: 'long' },
  lange: { gloss: 'long' },
  kort: { gloss: 'short' },
  mooi: { gloss: 'beautiful' },
  leuk: { gloss: 'nice, fun' },
  fijn: { gloss: 'pleasant' },
  duur: { gloss: 'expensive' },
  goedkoop: { gloss: 'cheap' },
  koud: { gloss: 'cold' },
  warm: { gloss: 'warm' },
  vroeg: { gloss: 'early' },
  druk: { gloss: 'busy' },
  rustig: { gloss: 'quiet' },
  belangrijk: { gloss: 'important' },
  klaar: { gloss: 'ready, finished' },
  thuis: { gloss: 'at home' },
  blij: { gloss: 'glad' },
  moe: { gloss: 'tired' },
  aardig: { gloss: 'kind, nice' },
  aardige: { gloss: 'kind, nice' },
  gezellig: { gloss: 'cosy, sociable' },
  interessant: { gloss: 'interesting' },
  kapot: { gloss: 'broken' },
  vrij: { gloss: 'free' },
  volgend: { gloss: 'next' },
  geachte: { gloss: 'dear (formal)' },
  beste: { gloss: 'dear; best' },
  lieve: { gloss: 'dear (affectionate)' },
  vriendelijke: { gloss: 'kind' },
  groet: { gloss: 'greeting' },
  groetjes: { gloss: 'regards …' },
  hoogachtend: { gloss: 'yours faithfully' },
  hoi: { gloss: 'hi' },
  hallo: { gloss: 'hello' },
  doei: { gloss: 'bye (informal)' },

  // Numbers and quantities
  twee: { gloss: 'two' },
  drie: { gloss: 'three' },
  vier: { gloss: 'four' },
  vijf: { gloss: 'five' },
  zes: { gloss: 'six' },
  zeven: { gloss: 'seven' },
  acht: { gloss: 'eight' },
  negen: { gloss: 'nine' },
  tien: { gloss: 'ten' },
  elf: { gloss: 'eleven' },
  twaalf: { gloss: 'twelve' },
  half: { gloss: 'half past …' },
  kwart: { gloss: 'quarter' },
  honderd: { gloss: 'hundred' },
  eerste: { gloss: 'first' },
  tweede: { gloss: 'second' },
  veertien: { gloss: 'fourteen' },

  // Words that turned up in the game texts
  te: { gloss: 'to; too …' },
  hele: { gloss: 'whole' },
  geboren: { gloss: 'born', verb: true },
  keer: { gloss: 'time, occasion' },
  weg: { gloss: 'away; road' },
  elke: { gloss: 'every' },
  engels: { gloss: 'English' },
  kop: { gloss: 'cup; head' },
  klas: { gloss: 'class' },
  buiten: { gloss: 'outside' },
  vind: { gloss: 'find; think', verb: true },
  hard: { gloss: 'hard, heavily' },
  later: { gloss: 'later' },
  vertraging: { gloss: 'delay' },
  mee: { gloss: 'along, with' },
  zeggen: { gloss: 'to say', verb: true },
  overnemen: { gloss: 'to take over', verb: true },
  pijn: { gloss: 'pain' },
  hopen: { gloss: 'to hope', verb: true },
  hoop: { gloss: 'hope …' },
  nummer: { gloss: 'number' },
  bevestigen: { gloss: 'to confirm', verb: true },
  bevestig: { gloss: 'confirm', verb: true },
  ontvangst: { gloss: 'receipt' },
  diensten: { gloss: 'services' },
  jarig: { gloss: 'birthday …' },
  nodig: { gloss: 'necessary …' },
  bijeenkomst: { gloss: 'gathering' },
  ergens: { gloss: 'somewhere' },
  reactie: { gloss: 'reply, reaction' },
  tegemoet: { gloss: 'towards …' },
  hand: { gloss: 'hand …' },
  huur: { gloss: 'rent' },
  beetje: { gloss: 'a little' },
  meer: { gloss: 'more' },
  mogelijk: { gloss: 'possible …' },
  regenen: { gloss: 'to rain', verb: true },
  regent: { gloss: 'rains', verb: true },
  per: { gloss: 'by, per' },
  mail: { gloss: 'mail' },
  'e-mail': { gloss: 'email' },
  'e-mailadres': { gloss: 'email address' },
  werkwoord: { gloss: 'verb' },
  werkwoorden: { gloss: 'verbs' },
  hier: { gloss: 'here' },
  hieronder: { gloss: 'below' },
  tik: { gloss: 'tap', verb: true },
  tikken: { gloss: 'to tap', verb: true },
  roken: { gloss: 'to smoke', verb: true },
  rookt: { gloss: 'smokes', verb: true },
  dichtdoen: { gloss: 'to close', verb: true },
  opruimen: { gloss: 'to tidy up', verb: true },
  uitgaan: { gloss: 'to go out', verb: true },
  poging: { gloss: 'attempt' },
}

/** Looks a word up, ignoring case and surrounding punctuation. */
export function lookupWord(raw: string): GlossEntry | null {
  const word = raw.toLowerCase().replace(/^[^a-zà-ÿ]+|[^a-zà-ÿ]+$/g, '')
  if (word.length === 0) return null
  return glossary[word] ?? null
}
